sudo: false
language: scala
jdk: oraclejdk8
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-M5

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
