sudo: false

language: scala

scala:
  - 2.11.7
  - 2.10.6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk: oraclejdk8

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
